from __future__ import annotations

from predictive_representations_rl.envs.base import DatasetSpec, EnvSpec

EXORL_DATA_DIR = "~/.exorl/data"


def exorl_rnd_dataset(domain: str) -> DatasetSpec:
    """The ExORL RND dataset as generated by third_party/onestep-fb/data_gen_scripts."""
    return DatasetSpec(
        name="exorl_rnd",
        observation_type="state",
        files=(
            f"{EXORL_DATA_DIR}/rnd-{domain}.hdf5",
            f"{EXORL_DATA_DIR}/rnd-{domain}-val.hdf5",
        ),
        how_to_get=(
            "cd third_party/onestep-fb && "
            f"sh data_gen_scripts/exorl_download.sh {domain} rnd && "
            f"PYTHONPATH=. .venv/bin/python data_gen_scripts/generate_exorl_dataset.py --domain_name={domain} "
            f"--save_path={EXORL_DATA_DIR}/rnd-{domain}.hdf5 && "
            f"PYTHONPATH=. .venv/bin/python data_gen_scripts/generate_exorl_dataset.py --domain_name={domain} "
            f"--save_path={EXORL_DATA_DIR}/rnd-{domain}-val.hdf5 --skip_size=5_000_000 --dataset_size=100_000"
        ),
    )


POINT_MASS_MAZE = EnvSpec(
    name="point_mass_maze",
    suite="dmc",
    description="2D point mass in a four-goal maze (ExORL custom DMC task).",
    tasks=("reach_top_left", "reach_top_right", "reach_bottom_left", "reach_bottom_right"),
    action_type="continuous",
    observation_types=frozenset({"state", "pixels"}),
    datasets={"exorl_rnd": exorl_rnd_dataset("point_mass_maze")},
    native_names={
        # FB pretrains on the domain's dataset and is evaluated zero-shot on every task.
        "onestep_fb": lambda task, obs_type: "exorl-rnd-point_mass_maze",
        # Dreamer picks state vs. pixels through its config (dmc_proprio / dmc_vision), not the task name.
        "dreamerv3": lambda task, obs_type: f"dmc_point_mass_maze_{task}",
    },
)
